"""Selenium-powered browser fallback for difficult download pages."""

from __future__ import annotations

import importlib.util
import time
from dataclasses import dataclass
from pathlib import Path

from ..errors import DependencyMissingError, VlpError

ANTI_CRAWL_MARKERS = (
    "403",
    "forbidden",
    "captcha",
    "verification",
    "verify you are human",
    "sign in",
    "login required",
    "cookies",
    "cookie",
    "access denied",
    "temporarily unavailable",
)


@dataclass(slots=True)
class SeleniumContext:
    """Browser-derived context used to retry yt-dlp."""

    original_url: str
    resolved_url: str
    page_title: str
    user_agent: str
    referer: str
    cookie_file: Path


class SeleniumFallbackError(VlpError):
    """Raised when Selenium fallback cannot produce a usable browser context."""

    def __init__(self, message: str, hint: str | None = None) -> None:
        super().__init__(message=message, error_code="DOWNLOAD_FAILED", hint=hint)


def selenium_extra_available() -> bool:
    """Return whether the optional Selenium dependencies are installed."""
    return (
        importlib.util.find_spec("selenium") is not None
        and importlib.util.find_spec("webdriver_manager") is not None
    )


def should_attempt_selenium_fallback(mode: str, error_message: str | None) -> bool:
    """Decide whether Selenium fallback should run for the given mode and failure."""
    normalized_mode = (mode or "auto").strip().lower()
    if normalized_mode == "off":
        return False
    if normalized_mode == "on":
        return True
    if normalized_mode != "auto":
        return False
    if not error_message:
        return False

    lowered = error_message.lower()
    return any(marker in lowered for marker in ANTI_CRAWL_MARKERS)


def run_selenium_browser_context(*, url: str, workspace_dir: str | Path) -> SeleniumContext:
    """Open the URL in Selenium and export cookies plus useful request context."""
    if not selenium_extra_available():
        raise DependencyMissingError(
            "selenium fallback requested but optional dependencies are not installed",
            hint="install with: pip install 'video-link-pipeline[selenium]'",
        )

    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options
    from selenium.webdriver.chrome.service import Service as ChromeService
    from webdriver_manager.chrome import ChromeDriverManager

    workspace = Path(workspace_dir)
    workspace.mkdir(parents=True, exist_ok=True)
    cookie_file = workspace / "selenium-cookies.txt"

    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--window-size=1280,900")
    options.add_argument("--lang=zh-CN")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)

    driver = webdriver.Chrome(
        service=ChromeService(ChromeDriverManager().install()),
        options=options,
    )
    try:
        driver.set_page_load_timeout(45)
        driver.get(url)
        time.sleep(5)
        _wait_for_document_ready(driver)
        time.sleep(2)

        resolved_url = driver.current_url or url
        if not resolved_url:
            raise SeleniumFallbackError("selenium fallback could not resolve a usable page URL")

        user_agent = str(driver.execute_script("return navigator.userAgent") or "")
        page_title = str(driver.title or "")
        _write_netscape_cookies(cookie_file, driver.get_cookies())

        return SeleniumContext(
            original_url=url,
            resolved_url=resolved_url,
            page_title=page_title,
            user_agent=user_agent,
            referer=resolved_url,
            cookie_file=cookie_file,
        )
    except Exception as exc:
        raise SeleniumFallbackError(
            "selenium fallback could not prepare browser context",
            hint=str(exc),
        ) from exc
    finally:
        driver.quit()


def _wait_for_document_ready(driver: object) -> None:
    try:
        from selenium.webdriver.support.ui import WebDriverWait

        WebDriverWait(driver, 15).until(
            lambda current: current.execute_script("return document.readyState") == "complete"
        )
    except Exception:
        return


def _write_netscape_cookies(cookie_file: Path, cookies: list[dict[str, object]]) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by video-link-pipeline Selenium fallback",
    ]

    for cookie in cookies:
        domain = str(cookie.get("domain") or "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(cookie.get("path") or "/")
        secure = "TRUE" if bool(cookie.get("secure")) else "FALSE"
        expiry = str(int(cookie.get("expiry", 0) or 0))
        name = str(cookie.get("name") or "")
        value = str(cookie.get("value") or "")
        lines.append("\t".join([domain, include_subdomains, path, secure, expiry, name, value]))

    cookie_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
